#!/usr/bin/env python3
"""
DTN Node Setup Wizard — generates ION-DTN configuration and starts the node.

Creates all required ION config sections (ionadmin, bpadmin, ipnadmin, ionsecadmin)
and optionally sets up dtnex, IPND, and systemd services.
"""

import os
import sys
from pathlib import Path


def prompt(msg, default=None):
    if default:
        val = input(f"{msg} [{default}]: ").strip()
        return val if val else default
    return input(f"{msg}: ").strip()


def confirm(msg, default=True):
    suffix = " [Y/n]: " if default else " [y/N]: "
    val = input(msg + suffix).strip().lower()
    if not val:
        return default
    return val in ("y", "yes")


def generate_ionrc(cfg):
    """Generate the ionadmin section of host.rc."""
    ipn = cfg["ipn"]
    gateway = cfg["gateway_ipn"]
    rate = cfg["contact_rate"]
    duration = cfg["contact_duration"]
    owlt = cfg["owlt"]

    lines = [
        "## begin ionadmin",
        f"1 {ipn} ''",
        "s",
        "",
        f"# Contact with gateway ({gateway})",
        f"a contact +1 +{duration} {ipn} {gateway} {rate}",
        f"a contact +1 +{duration} {gateway} {ipn} {rate}",
        "",
        f"# Range with gateway",
        f"a range +1 +{duration} {ipn} {gateway} {owlt}",
        f"a range +1 +{duration} {gateway} {ipn} {owlt}",
        "",
        "# Loopback",
        f"a contact +1 +{duration} {ipn} {ipn} {rate}",
        f"a range +1 +{duration} {ipn} {ipn} {owlt}",
        "",
        "m production 1000000",
        "m consumption 1000000",
        "e 1",
        "## end ionadmin",
    ]
    return "\n".join(lines)


def generate_bprc(cfg):
    """Generate the bpadmin section."""
    ipn = cfg["ipn"]
    gateway_ip = cfg["gateway_ip"]
    port = cfg["udp_port"]

    lines = [
        "## begin bpadmin",
        "1",
        "a scheme ipn 'ipnfw' 'ipnadminep'",
        "",
        "# Local endpoints",
        f"a endpoint ipn:{ipn}.1 q",
        f"a endpoint ipn:{ipn}.2 q",
        f"a endpoint ipn:{ipn}.3 q",
        f"a endpoint ipn:{ipn}.4 q",
        f"a endpoint ipn:{ipn}.5 q",
        f"a endpoint ipn:{ipn}.64 q",
        f"a endpoint ipn:{ipn}.65 q",
        "",
        "# UDP protocol",
        "a protocol udp 1400 100",
        "",
        "# Listen on all interfaces",
        f"a induct udp 0.0.0.0:{port} udpcli",
        "",
        "# Outducts",
        f"a outduct udp {gateway_ip}:{port} udpclo",
        f"a outduct udp 127.0.0.1:{port} udpclo",
        "",
        "s",
        "e 1",
        "## end bpadmin",
    ]
    return "\n".join(lines)


def generate_ipnrc(cfg):
    """Generate the ipnadmin section."""
    ipn = cfg["ipn"]
    gateway = cfg["gateway_ipn"]
    gateway_ip = cfg["gateway_ip"]
    port = cfg["udp_port"]

    lines = [
        "## begin ipnadmin",
        f"# Gateway ({gateway})",
        f"a plan {gateway} udp/{gateway_ip}:{port}",
        "",
        "# Loopback",
        f"a plan {ipn} udp/127.0.0.1:{port}",
        "",
        "e 1",
        "## end ipnadmin",
    ]
    return "\n".join(lines)


def generate_ionsecrc():
    """Generate the ionsecadmin section."""
    return "## begin ionsecadmin\n1\ne 1\n## end ionsecadmin"


def generate_dtnex_conf(cfg):
    """Generate dtnex.conf."""
    return f"""# DTNEx configuration
# Generated by dtn-tools init

updateInterval=1800
bundleTTL=1800
contactLifetime=3600
contactTimeTolerance=1800
presSharedNetworkKey=open
nodemetadata="{cfg['node_name']},{cfg['email']},{cfg['location']}"
gpsLatitude={cfg.get('lat', '0.0')}
gpsLongitude={cfg.get('lon', '0.0')}
createGraph=true
graphFile={cfg['dtn_dir']}/contactGraph.png
serviceMode=true
debugMode=false
noMetadataExchange=false
"""


def generate_discovery_conf(cfg):
    """Generate discovery.conf."""
    return f"""# DTN Discovery Configuration
# Generated by dtn-tools init

my_ipn={cfg['ipn']}
gateway_ipn={cfg['gateway_ipn']}
scan_interval=300
openipn_metadata_url=https://openipn.org/metadata_list.txt
openipn_graph_url=https://openipn.org/contactGraph.gv
local_metadata_file={cfg['dtn_dir']}/nodesmetadata.txt
discovered_db={cfg['dtn_dir']}/dtn-discovery/discovered_nodes.json
log_file={cfg['dtn_dir']}/dtn-discovery/discovery.log
auto_add_contacts=true
auto_add_via_gateway=true
contact_rate=100000
contact_duration=360000000
owlt=1
ipnd_enabled=true
ipnd_config={cfg['dtn_dir']}/dtn-discovery/ipnd.rc
debug=false
"""


def generate_ipnd_rc(cfg):
    """Generate IPND configuration."""
    ipn = cfg["ipn"]
    port = cfg["udp_port"]
    listen_ip = cfg.get("listen_ip", "0.0.0.0")
    broadcast = cfg.get("broadcast_ip", "255.255.255.255")

    return f"""## IPND configuration
## Generated by dtn-tools init
1
e 1
m eid ipn:{ipn}.0
m port 4550
m announce period 1
m announce eid 1
m interval unicast 10
m interval multicast 30
m interval broadcast 30
m multicast ttl 255
a svcadv CLA-UDP-v4 IP:{listen_ip} Port:{port}
a listen 0.0.0.0
a destination {broadcast}
s
"""


def generate_systemd_services(cfg):
    """Generate systemd service files."""
    user = cfg["user"]
    dtn_dir = cfg["dtn_dir"]
    services = {}

    services["dtn-discovery"] = f"""[Unit]
Description=DTN Neighbor Discovery Daemon
After=network.target

[Service]
Type=simple
User={user}
WorkingDirectory={dtn_dir}/dtn-discovery
ExecStart=/usr/bin/python3 {dtn_dir}/dtn-discovery/discovery.py
Restart=on-failure
RestartSec=30
Environment=PATH=/usr/local/bin:/usr/bin:/bin

[Install]
WantedBy=multi-user.target
"""

    services["dtnex"] = f"""[Unit]
Description=DTN Exchange (dtnex) metadata service
After=network.target

[Service]
Type=simple
User={user}
WorkingDirectory={dtn_dir}
ExecStart=/usr/local/bin/dtnex {dtn_dir}/dtnex.conf
Restart=on-failure
RestartSec=30
Environment=PATH=/usr/local/bin:/usr/bin:/bin

[Install]
WantedBy=multi-user.target
"""

    services["bpecho"] = f"""[Unit]
Description=DTN bpecho service
After=network.target

[Service]
Type=simple
User={user}
ExecStart=/usr/local/bin/bpecho ipn:{cfg['ipn']}.12161
Restart=on-failure
RestartSec=10
Environment=PATH=/usr/local/bin:/usr/bin:/bin

[Install]
WantedBy=multi-user.target
"""

    return services


def run_init(args):
    """Run the interactive setup wizard."""
    print("=" * 60)
    print("  DTN Node Setup Wizard")
    print("  Generates ION-DTN configuration for your node")
    print("=" * 60)
    print()

    # Gather configuration
    cfg = {}

    cfg["ipn"] = args.ipn or prompt("Your IPN node number (from openipn.org)")
    cfg["node_name"] = args.name or prompt("Node name", f"dtn-node-{cfg['ipn'][-3:]}")
    cfg["email"] = args.email or prompt("Contact email")
    cfg["location"] = prompt("Location (city, country)", "")
    cfg["lat"] = prompt("GPS latitude (optional)", "0.0")
    cfg["lon"] = prompt("GPS longitude (optional)", "0.0")
    cfg["user"] = prompt("Linux username", os.environ.get("USER", "pi"))
    cfg["dtn_dir"] = prompt("DTN directory", f"/home/{cfg['user']}/dtn")
    cfg["gateway_ipn"] = prompt("Gateway IPN", "268485000")
    cfg["gateway_ip"] = prompt("Gateway IP (Tailscale/VPN)", "100.96.108.37")
    cfg["udp_port"] = prompt("UDP port", "4556")
    cfg["contact_rate"] = prompt("Contact rate (bytes/sec)", "100000")
    cfg["contact_duration"] = prompt("Contact duration (seconds)", "360000000")
    cfg["owlt"] = prompt("One-way light time (seconds)", "1")
    cfg["listen_ip"] = prompt("Listen IP for IPND", "0.0.0.0")
    cfg["broadcast_ip"] = prompt("Broadcast address for IPND beacons", "255.255.255.255")

    print()
    print("Configuration:")
    print(f"  IPN:      ipn:{cfg['ipn']}")
    print(f"  Name:     {cfg['node_name']}")
    print(f"  Gateway:  ipn:{cfg['gateway_ipn']} at {cfg['gateway_ip']}")
    print(f"  DTN Dir:  {cfg['dtn_dir']}")
    print()

    if not confirm("Generate configuration files?"):
        print("Cancelled.")
        return

    dtn_dir = Path(cfg["dtn_dir"])

    # Create directories
    dtn_dir.mkdir(parents=True, exist_ok=True)
    (dtn_dir / "dtn-discovery").mkdir(exist_ok=True)
    (dtn_dir / "scripts").mkdir(exist_ok=True)
    (dtn_dir / "logs").mkdir(exist_ok=True)

    # Generate ION host config
    host_rc = dtn_dir / f"host{cfg['ipn']}.rc"
    sections = [
        "# INITIALIZE",
        "",
        generate_ionrc(cfg),
        "",
        "",
        generate_bprc(cfg),
        "",
        "",
        generate_ipnrc(cfg),
        "",
        "",
        generate_ionsecrc(),
        "",
    ]
    host_rc.write_text("\n".join(sections))
    print(f"  Created: {host_rc}")

    # Generate dtnex.conf
    dtnex_conf = dtn_dir / "dtnex.conf"
    dtnex_conf.write_text(generate_dtnex_conf(cfg))
    print(f"  Created: {dtnex_conf}")

    # Generate discovery.conf
    disc_conf = dtn_dir / "dtn-discovery" / "discovery.conf"
    disc_conf.write_text(generate_discovery_conf(cfg))
    print(f"  Created: {disc_conf}")

    # Generate IPND config
    ipnd_rc = dtn_dir / "dtn-discovery" / "ipnd.rc"
    ipnd_rc.write_text(generate_ipnd_rc(cfg))
    print(f"  Created: {ipnd_rc}")

    # Copy discovery daemon
    src_dir = Path(__file__).parent
    discovery_src = src_dir / "discovery.py"
    discovery_dst = dtn_dir / "dtn-discovery" / "discovery.py"
    if discovery_src.exists():
        import shutil
        shutil.copy2(discovery_src, discovery_dst)
        discovery_dst.chmod(0o755)
        print(f"  Copied:  {discovery_dst}")

    # Generate systemd services
    if confirm("\nInstall systemd services?"):
        services = generate_systemd_services(cfg)
        for name, content in services.items():
            svc_path = Path(f"/etc/systemd/system/{name}.service")
            try:
                svc_path.write_text(content)
                print(f"  Created: {svc_path}")
            except PermissionError:
                print(f"  SKIP:    {svc_path} (need sudo)")
                tmp_path = Path(f"/tmp/{name}.service")
                tmp_path.write_text(content)
                print(f"  Saved:   {tmp_path} (copy to /etc/systemd/system/ with sudo)")

    print()
    print("Setup complete!")
    print()
    print("Next steps:")
    print(f"  1. Start ION:       ionstart -I {host_rc}")
    print(f"  2. Start dtnex:     cd {dtn_dir} && dtnex dtnex.conf")
    print(f"  3. Start discovery: dtn-discovery (or systemctl start dtn-discovery)")
    print(f"  4. Check status:    dtn status")
    print()
    print("To add neighbors:")
    print(f"  dtn neighbors add <IPN> <IP>")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--ipn", help="IPN node number")
    parser.add_argument("--name", help="Node name")
    parser.add_argument("--email", help="Contact email")
    run_init(parser.parse_args())
